<template>
  <div class="mb-16 items-center">
    <div class="max-w-lg mx-auto">
      <div class="flex justify-center mb-6">
        <div>
          <img
            src="/welcome/content-light.svg"
            alt="welcome image"
            height="100"
            class="light-img w-full"
          />
          <img
            src="/welcome/content-dark.svg"
            alt="welcome image"
            class="dark-img w-full"
          />
        </div>
        <div>
          <img
            src="/welcome/nuxt-light.svg"
            alt="welcome image"
            class="light-img w-full"
          />
          <img
            src="/welcome/nuxt-dark.svg"
            alt="welcome image"
            class="dark-img w-full"
          />
        </div>
      </div>
      <div class="xl:text-lg font-medium leading-relaxed text-center">
        <p>
          You are looking at the default template generated by the
          <b>create-nuxt-blog</b>
          CLI. To start customizing it, check out the
          <a href="https://nuxtjs.blog" target="_blank"
            ><u><b>docs</b></u></a
          >.
        </p>
      </div>
    </div>
  </div>
</template>
